#!/bin/bash

# Check if the output file was passed as the first argument:
if [ -z $1 ]; then
	echo "No ouput file provided."
	exit 0
fi

echo "#################################################################################"
echo "Job $1"
echo "#################################################################################"
egrep -h "$(grep -h 'Step number' $1 | wc -l) out of" $1 | tail -1
egrep -h 'Converged' $1 | tail -1
egrep -h 'YES| NO | exceeded' $1 | tail -4
egrep -h 'SCF Don' $1 | tail -1
echo "#################################################################################"

