#!/bin/bash

# Check if the output file was passed as the first argument:
if [[ -z $@ ]]; then
        echo "No ouput file provided."
        exit 0
fi

for var in "$@"
do
  echo "#################################################################################"
  echo "Job $var"
  echo "#################################################################################"
  egrep -h "$(grep -h 'Step number' $var | wc -l) out of" $var | tail -1
  egrep -h 'Converged' $var | tail -1
  egrep -h 'YES| NO | exceeded' $var | tail -4
  egrep -h 'SCF Don' $var | tail -1
  echo "#################################################################################"
done
