#!/bin/bash

# Check if the output file was passed as the first argument:
  if  [[ -z $@ ]]; then
        echo "#####################################################"
        echo "# This script was made by Manoel Barrionuevo - 2017 #"
        echo "#---------------------------------------------------#"
        echo "# In order to get the energy value of your optmized #"
        echo "#structure, type the following:                     #"
        echo "#             getenergy <filename.log>              #"
        echo "# where <filename.log> is your gaussian output.     #"
        echo "#####################################################"
        exit 0
  else
        for var in "$@"
        do
                energy=$(grep "SCF Done" $var | tail -1 | awk '{print $5}')
                echo "$var : $energy au"
        done
  fi
