#!/bin/bash

# Check if the output file was passed as the first argument:
if [[ -z $@ ]]; then
	echo "#####################################################"
	echo "# This script was made by Manoel Barrionuevo - 2017 #"
	echo "#---------------------------------------------------#"
	echo "# In order to get the last xyz coordinates you shall#"
	echo "#type the following:                                #"
	echo "#            takelastxyz <filename.log>             #"
	echo "# where <filename.log> is your gaussian output.     #"
	echo "#---------------------------------------------------#"
        echo "# This is going to generate a PDB and XYZ files.    #"
        echo "# Obabel is used to create the PDB file, thus make  #"
	echo "#sure your installed version is at default location.#"
	echo "#####################################################"
	exit 0
fi

if ! which obabel > /dev/null; then
  echo "#################################"
  echo "#   PLEASE INSTALL OPEN-BABEL   #"
  echo "#################################"
  exit
fi

echo "#################################"
echo "#    GETTING NUMBER OF ATOMS    #"
echo "#################################"

for var in $@
do
	line=$(grep -h "Stoichiometry" $var | tail -1 | grep -Eo "[0-9\.]+" | awk '{ SUM += $1} END { print SUM}')

	let lines=line+5
	let lin=line+1

	echo "#################################"
	echo "#      GREPPING COORDINATES     #"
	echo "#################################"

	grep -A$lines "Standard orientation" $var | tail -$lines | sed -e 's/---/ /g' | grep -A$line "^\ " | tail -$lin | awk '{print $2 " " $4 " " $5 " " $6}' | sed '/constants /d' > $var.xyz

	echo "#################################"
	echo "#      RENAMING ATOM CODES      #"
	echo "#################################"

	sed -i 's/^1\ /H /g' $var.xyz
	sed -i 's/^6\ /C /g' $var.xyz
	sed -i 's/^7\ /N /g' $var.xyz
	sed -i 's/^8\ /O /g' $var.xyz
	sed -i 's/^15\ /P /g' $var.xyz
	sed -i 's/^16\ /S /g' $var.xyz
	sed -i 's/^79\ /Au /g' $var.xyz

	echo "#################################"
	echo "#        MAKING PDB FILE        #"
	echo "#################################"

	sed -e '/^\ /d' $var.xyz > $var.2xyz
	sed -i "1s/^/$line\n\n/" $var.2xyz
	obabel -ixyz $var.2xyz -opdb -O $var.pdb
	rm -rf $var.2xyz

	echo "#################################"
	echo "#      CHANGING FILE NAME       #"
	echo "#################################"

	for j in *.log.xyz; do mv -v -- "$j" "${j%.log.xyz}.xyz"; done
	for j in *.log.pdb; do mv -v -- "$j" "${j%.log.pdb}.pdb"; done

	echo "#################################"
	echo "#             DONE              #"
	echo "#################################"
done
